### ISSUE TITLE
Feature A

### ISSUE THREAD

**Issue by cov1983** [cov1983/SO2_Praxisarbeit#1]
**Es sollte eine Feature Funktion implementiert werden.**
Den State ist schon vorhanden, es muss das Modul entwickelt werden (.c / .h Files).
Als Beispiel könnte man die Min/Max Werte detektieren, es muss aber einfach bleiben da wir nicht so viel Zeit haben!

**Comment by cov1983** [comment]
Ich habe eine neue Branch Feature-A erstellt, du kannst dort alles mögliches machen !

**Comment by swissMAG** [comment]
Feature eingebaut, benötige aber noch eine Möglichkeit um mit PB1 einen Counter hochzuzählen, ohne einen Interrpt auszulösen? Eine Idee?

Muss die Sache noch ein wenig Kommentieren. Mache ich heute noch.

**Comment by cov1983** [comment]
Ich habe die Feature ins develop branch integriert, als erste Demo funtioniert sie gut 👍
